### ISSUE TITLE
feat: On map page, update the Stanley Nelson Centre

### ISSUE THREAD

**Issue by AndrewDNelson** [bouceka/twu-companion#30]
Change the "Stanley Nelson centre" to be named "Robert N. Thompson".
![IMG_DC75D1C8B20C-1](https://github.com/bouceka/twu-companion/assets/105749054/77b55a06-b7c4-48c2-b1a7-5113a67e2c66)

**Comment by bouceka** [comment]
This one is correct. They are two separate buildings that are connected. 
Campus map: 
<img width="94" alt="Screenshot 2024-04-07 at 1 15 19 PM" src="https://github.com/bouceka/twu-companion/assets/49728880/7ac0d470-81ee-4ab7-a7d9-32a9e9605a86">
Buildings: 
<img width="153" alt="Screenshot 2024-04-07 at 1 15 23 PM" src="https://github.com/bouceka/twu-companion/assets/49728880/dc17c14e-1334-418a-b876-8f16db1517c9">
<img width="131" alt="Screenshot 2024-04-07 at 1 15 28 PM" src="https://github.com/bouceka/twu-companion/assets/49728880/550685e9-543b-4364-aa4c-2107938006e5">

They used to be separate tho: 
[Archive](https://archivessearch.twu.ca/stanley-nelson-centre-and-robert-n-thompson-centre-renovations-5)

**Comment by AndrewDNelson** [comment]
The thing is though, the sign out front of it says RNT which is what people look for when going to classes. An alternative to switching them is just add a second location for RNT

**Comment by bouceka** [comment]
Okok, I'll remove the Stanley Nelson Center, or I'll comment for now.
